name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: install task
        run: curl -Ls https://git.io/ttask.sh | sh
      - name: run tests
        run: ./bin/task test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: install task
        run: curl -Ls https://git.io/ttask.sh | sh
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
      - name: run linter
        run: ./bin/task lint
  build:
    name: Build binary
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test, lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: install task
        run: curl -Ls https://git.io/ttask.sh | sh
      - run: ./bin/task bin
      - run: mv ci-build/downtime ci-build/downtime_${{ matrix.goos }}_${{ matrix.goarch }}
      - uses: actions/upload-artifact@master
        with:
          name: build-artifacts
          path: ci-build
  release:
    name: Release binary
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: install changelogger
        run: curl -Ls https://git.io/changelogger.sh | sh
      - uses: actions/download-artifact@master
        with:
          name: build-artifacts
          path: ci-build
      - name: Save changelog entries of current release
        run: ./bin/changelogger release last > CHANGELOG_RELEASE.md
      - name: Print changelog entries for debugging
        run: cat CHANGELOG_RELEASE.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ci-build/*
          body_path: CHANGELOG_RELEASE.md
          token: ${{ secrets.GITHUB_TOKEN }}
